http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  user-api:
    host: localhost
    paths: ['/user/*','/login','/reset-password','/forgot-password','/change-password','/request-email-confirm','/confirm-email','/signup','/create-admin','/login-with-google']
  main-api:
    host: localhost
    paths: '*'
serviceEndpoints:
  user-sv:
    url: 'http://tiyosys.ml:1338'
  main-sv:
    url: http://tiyosys.ml:1339'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  user:
    apiEndpoints:
      - user-api
    policies:
      - proxy:
        - action:
            serviceEndpoint: user-sv
            changeOrigin: true
  main:
    apiEndpoints:
      - main-api
    policies:
      - proxy:
        - action:
            serviceEndpoint: main-sv
            changeOrigin: true
